apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netflix-backend
  template:
    metadata:
      labels:
        app: netflix-backend
    spec:
      containers:
      - name: backend
        image: <ECR_BACKEND_IMAGE>
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: netflix-backend
spec:
  selector:
    app: netflix-backend
  ports:
  - port: 5000
    targetPort: 5000
